### ISSUE TITLE
Exit upon test failure

### ISSUE THREAD

**Issue by mbeko** [pgrange/bash_unit#10]
Due to the `exit 1` in the `fail()` function, tests are aborted when an assertion fails. In such a case, the `teardown()` function is not called which potentially leaves a mess behind. I would expect `teardown()` to be always called, independently of the test success.

I made a quick try to change `exit 1` to `return 1` but that did not work, so I did not investigate further for the moment.

**Comment by pgrange** [comment]
Thank you for your issue.

I interpreted this as an acceptable behavior at the moment of the writing of the teardown function but I too find this is actually not acceptable and leaves a mess.

Will fix that.

**Comment by mbeko** [comment]
Thanks! If you think it's more a matter of opinion, maybe you can make it configurable.

As far as I am concerned, I had to write a check in my `setup()` if `teardown()` had been called the last time and if it did not, call it again before doing the actual setup.

**Comment by pgrange** [comment]
teardown will now be run after every test, even in case of test failure.

Regards,

**Comment by mbeko** [comment]
Great, thanks! I'll try it out :)

**Comment by mbeko** [comment]
Just to let you know, `teardown()` is now always executed as expected.

But now failed assertions don't exit the test function as well. I don't consider it as huge a problem as the one with `teardown()`, but it's a bit unusual compared to usual unit test frameworks for other languages.

So you might want to adapt the code in a way to always execute `teardown()` _and_ exit test functions upon failed assertions.

**Comment by pgrange** [comment]
Than you for you feedback @mbeko 

I do not totally understand the issue here.

Would you mind giving me some basic code that reproduce the issue you describe with a description of what you expect to see and what you actually observe ?

That would be very helpfull.

Regards.

**Comment by mbeko** [comment]
No problem, here's an example test:
```bash
#!/bin/bash

teardown() {
    echo "teardown() executed"
}

test_failing_assertions() {
    assert true
    assert false
    assert true
    assert false
    assert true
}
```
The output is:
```
Running test_failing_assertions... FAILURE
test_exit_upon_failure.sh:5:test_failing_assertions()
FAILURE
test_exit_upon_failure.sh:7:test_failing_assertions()
SUCCESS
teardown() executed
```
My expectation is:
```
Running test_failing_assertions... FAILURE
test_exit_upon_failure.sh:5:test_failing_assertions()
teardown() executed
```
So I would like to return from the test when the first assertion fails. But the whole script should not exit, so that `teardown()` will be run.

Sinon je parle français si ça t'aiderait mieux comprendre mes explications.

**Comment by pgrange** [comment]
Thank you.

With your code sampl, the issue is crystal clear.

Dites-le avec du code.

**Comment by pgrange** [comment]
Hi @mbeko, 

Just pushed a new version that should fix this issue.

Regards,

**Comment by mbeko** [comment]
Thanks, looks good! :)
