### ISSUE TITLE
Impossible to fake commands containing hyphens

### ISSUE THREAD

**Issue by mbeko** [pgrange/bash_unit#11]
Commands which contain hyphens, e.g. `ssh-add`, cannot be mocked with `fake()` because this substitutes the command with a mock function, and apparently function names are not allowed to contain this character.

**Comment by pgrange** [comment]
You are right. fake defines a function to override the command and you can not use hyphens in bash function definitions.

So there is no way to fix that issue with the current implementation.

I keep this issue open until I fix the documentation to make this point as clear as possible.

In the mean time, if you have any suggestion to work around this issue I would be glad to read about them.

Happy to see you are still using bash_unit,
Regards.

P.S. I'll be AFK for several days, will probably take a look next monday

**Comment by mbeko** [comment]
One idea I had was to offer a second `fake()` function which uses aliases. These allow hyphens, at least in my version of Bash.

The problem with such a solution is that aliases are not inherited by subshells as far as I know. So a script under test could not be called normally, but it would be necessary to source it.

Otherwise one could replace the command with a script of the same name, e.g. via symbolic link or some way to overlap the original command. 

I like the fact that bash_unit is only one file with all the basic testing functionality, so I'm still using it :)

**Comment by pgrange** [comment]
You are right, aliases are not inherited.

Another issue with aliases is that they are not, by default, expanded in not interactive shells.

We may activate it in bash-unit with shopt but it may introduce other issues.

**Comment by pgrange** [comment]
Looking deeper into your issue, I was not able to reproduce it. For instance the following code will override ssh-add and just works:

```bash
#> cat test_hyphens 
test_one_can_override_ssh_add() {
  fake ssh-add echo key added

  assert_equals "key added" "$(ssh-add)"
}

#> ./bash_unit test_hyphens 
Running tests in test_hyphens
Running test_one_can_override_ssh_add... SUCCESS
`̀``

**Comment by mbeko** [comment]
> [...] but it may introduce other issues.
>
> [...] Might be hard to maintain.

I think those are rather not-so-nice workarounds, too. I understand that it may not be worth the effort for a problem which probably won't occur that often. At least the issue is documented just in case someone stumbles upon the same bug.

> Is it possible that you are not bash [...]?

Indeed, I use zsh on the command line, but my scripts all have `#!/bin/bash` in the first line. When I had been investigating the problem on the command line, I always started bash first.

> This question has interesting answers on this subject

I had read that as well and was a bit puzzled why it doesn't work for me although they write that it should work in bash. But as the hyphen is not listed in the documentation, I thought it's just undefined behaviour and not recommended anyway.

> For instance the following code will override ssh-add and just works

Works here, too, but my test setup is more complex. I constructed a minimal example with the relevant differences:
```bash
> cat test_hyphens
test_one_can_override_ssh_add() {
  fake ssh-add return 111

  ./script_under_test.sh

  assert_equals 111 $?
}
```
```bash
> cat script_under_test.sh
#!/bin/bash

call_ssh_add() {
    ssh-add
    return $?
}

call_ssh_add
exit $?
```
```
> ./bash_unit test_hyphens
Running tests in test_hyphens
Running test_one_can_override_ssh_add... /bin/bash: error importing function definition for `BASH_FUNC_ssh-add'
```
When you change `ssh-add` to `ssh_add`, the test is successful.

**Comment by pgrange** [comment]
Just out of curiosity, on what environment are you running the tests ?

On my case, unspecified hyphens are working on a Debian GNU/Linux 8 with GNU bash version 4.3.30(1)

**Comment by mbeko** [comment]
I ran the tests on Debian 7.10 with GNU bash 4.2.37(1).

What do you mean by "unspecified hyphens"? Did the tests from my last post run successfully on your system?

**Comment by pgrange** [comment]
Yep, does work on Debian 8 with bash 4.3.30 :

```bash
#> cat test_hyphens 
test_one_can_override_ssh_add() {
  fake ssh-add return 111

  ./script_under_test.sh

  assert_equals 111 $?
}
#> cat script_under_test.sh 
#!/bin/bash

call_ssh_add() {
    ssh-add
    return $?
}

call_ssh_add
exit $?
#> ./bash_unit test_hyphens 
Running tests in test_hyphens
Running test_one_can_override_ssh_add... SUCCESS
```

**Comment by mbeko** [comment]
Ah, good, so it looks like the problem is solved. I don't know whether this issue is worth a mention in the documentation since people can look it up here, but otherwise it can be closed, I guess.

Thanks for investigating!
