### ISSUE TITLE
`grep: write error: Broken pipe` when running tests

### ISSUE THREAD

**Issue by Pamplemousse** [pgrange/bash_unit#115]
When running tests in a "non-conventional" environment (during a `nix build`), I noticed that some complain about a broken pipe (but are still successful).

```bash
Running test_fail_fails ... /nix/store/11b3chszacfr9liy829xqknzp3q88iji-gnugrep-3.11/bin/grep: write error: Broken pipe
SUCCESS
```

I understand that [5d8953b9](https://github.com/pgrange/bash_unit/commit/5d8953b9) addressed a similar issue.

Internet searches pointed at a potential culprit: `SIGPIPE` being trapped (which happens in `nix build`, and on - some - CI/CD environments).

And indeed, one can reproduce the complaint by manually trapping `SIGPIPE`:

```bash
$ trap '' SIGPIPE
$ ./bash_unit -p test_fail_fails tests/test_core.sh 
Running tests in tests/test_core.sh
        Running test_fail_fails ... /nix/store/11b3chszacfr9liy829xqknzp3q88iji-gnugrep-3.11/bin/grep: write error: Broken pipe
SUCCESS ✓ 
Overall result: SUCCESS ✓ 
```

It's unclear to me how this situation should be handled, especially as I am not sure which pipe(s) may break.

As far as I can tell, only the following tests behave this way:

```text
test_assert_fails_fails
test_assert_shows_stderr_on_failure
test_assert_shows_stdout_on_failure
test_fail_fails
test_fail_prints_failure_message
```

**Comment by pgrange** [comment]
Interesting, thank you @Pamplemousse 

About [5d8953b9](https://github.com/pgrange/bash_unit/commit/5d8953b9), that you mention and that adresses the issue, the code also states:

```bash
  # I have no idea what is happening with these broken pipes on github actions
```

🤣

The fact that you managed to reproduce it locally should really help, thank you.

**Comment by pgrange** [comment]
Awesome, I've learned something here. Problem fixed, thank you @Pamplemousse 

I know it'll come kick me in the knees some day but I've decided to not write a test case for this one as it's quite an edge case and, actually, was a but in the test code.
