### ISSUE TITLE
There should be a screenshot or gif at the top of the README 

### ISSUE THREAD

**Issue by pgrange** [pgrange/bash_unit#118]
Extracted from @iambumblehead [comment](https://github.com/pgrange/bash_unit/pull/117#issuecomment-1998328342):

There should be a screenshot or gif at the top of the README bash-unit looks beautiful and its obvious when watching it run that this a good unit-testing tool with the things you need (whoever you are ☺️) I recently found that things like images can be excluded from releases and tags to keep the payload size small by adding something like the following to `.gitattributes`:

```
path/to/my.gif export-ignore
```

**Comment by iambumblehead** [comment]
A concept (feel free to ignore, of course); make a test file with maybe 10-20 tests. One of the tests fails or passes depending upon a value echo'd to a file "cookie-jar". Capture the shell as a gif around this sequence of commands and loop,
``` bash
$ bash_unit test/test*
# passing tests...
$ echo bug > cookie-jar
$ bash_unit test/test*
# failing tests...
$ echo cookie > cookie-jar
$ bash_unit test/test*
# passing tests...
$ echo bug > cookie-jar
$ bash_unit test/test*
# failing tests...
[...forever]
```

Show these things: "green" success passing results and "red" errors with useful error messages. How fast bash_unit feels, how useful the error messages are and how beautiful the output looks. They will show in the gif :)

Loop the gif seamlessly like this
<img src="https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExNGh2azB2aG9kNm91dm1nNWhiOHpsdng5MnhlbWVpMGFlaDR4YjhwYyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/d3YReFkgpI5bDWbm/giphy.gif" />
