### ISSUE TITLE
assert_matches failes with unescaped curly braces inside excepted string

### ISSUE THREAD

**Issue by slabstone** [pgrange/bash_unit#129]
`script.sh`
```
#!/bin/bash

echo 'Hello {} World!'
```

`test.sh`
```
#!/bin/bash

test_unscaped() {
  assert_matches 'Hello {} World!' "$(./script.sh)"
}

test_escaped() {
  assert_matches 'Hello \{\} World!' "$(./script.sh)"
}
```

Expected output:
```
$ bash_unit test.sh
Running tests in test.sh
        Running test_escaped ... SUCCESS ✓
        Running test_unscaped ... SUCCESS ✓
Overall result: SUCCESS ✓
```

Actual output:
```
$ bash_unit test.sh
Running tests in test.sh
        Running test_escaped ... SUCCESS ✓
        Running test_unscaped ... FAILURE ✗
 expected regex [Hello {} World!] to match [Hello {} World!]
test.sh:4:test_unscaped()
Overall result: FAILURE ✗
```

**Comment by pgrange** [comment]
Hi @slabstone and thank you for using bash_unit and submitting a wonderfully crafted issue 🎉 

Not sure what's happening yet but I wanted to share a first interesting observation that I can't reproduce on OsX with bash 5.2.26 but I can reproduce the issue on Debian with bash 5.2.15 🤔

**Comment by pgrange** [comment]
What a pickle! _assert_matches_  is using bash regex with the `=~` operator. This has some strange behavior with quotes and variable expansion. See https://stackoverflow.com/a/64071175

Here is an example script that uses this `=~` operator:

```bash
#!/bin/bash

actual='Hello {} World!'
expected_escaped="Hello \{\} World!"
expected_unescaped="Hello {} World!"

[[ "$actual" =~ $expected_escaped ]] && echo "Ok when {} is escaped"

[[ "$actual" =~ $expected_unescaped ]] || echo "Ko when {} is not escaped"
```

On Debian with bash 5.2.15 or Ubuntu with bash 5.2.21 we observe the following output when we run this script:
```
Ok when {} is escaped
Ko when {} is not escaped
```

Long story short, if you want to use the `=~` operator you need to escape `{}` symbols in your regex. bash_unit using this operator, you also need to escape it.

I'm sorry about that but, unless we change the way bash_unit checks regex (which I have no plan to do right now),  I'd say that this is the output to expect from your test:
```
$ bash_unit test.sh
Running tests in test.sh
        Running test_escaped ... SUCCESS ✓
        Running test_unscaped ... FAILURE ✗
 expected regex [Hello {} World!] to match [Hello {} World!]
test.sh:4:test_unscaped()
Overall result: FAILURE ✗
```
