### ISSUE TITLE
Optional message in assert method should add a space before stderr

### ISSUE THREAD

**Issue by guillaumevincent** [pgrange/bash_unit#15]
```
test_admin_can_execute_sudo_without_password(){
    run_ansible
    assert "grep 'admin ALL=(ALL) NOPASSWD: ALL' /etc/sudoers.d/admin" "admin is not sudoer"
}
```

![screenshot from 2016-09-13 11-24-26](https://cloud.githubusercontent.com/assets/943762/18468595/ecda7bf2-79a4-11e6-837a-2e06d7c8aa6e.png)

optional message in assert method should print stderr on a new line.

`admin is not sudoer grep: /etc/sudoers.d/admin: No such file or directory`
instead of 
`admin is not sudoergrep: /etc/sudoers.d/admin: No such file or directory`

**Comment by pgrange** [comment]
Fixed by #16

**Comment by pgrange** [comment]
@guillaumevincent  for your eyes only I detailed the path to displaying stdout and stderr in assert, assert_fail and assert_status_code without repeating ourselves.

See commits in branch assert_print_stdout_stderr https://github.com/pgrange/bash_unit/commits/assert_print_stdout_stderr

... easier when done sooner and with less beer

**Comment by guillaumevincent** [comment]
thanks for the detailed version :)
