### ISSUE TITLE
man bash_unit 

### ISSUE THREAD

**Issue by pgrange** [pgrange/bash_unit#19]
Now that work is in progress to package bash_unit, it needs its corresponding man page.

**Comment by n0vember-** [comment]
I've tried using md2man in order to generate man page from the git README.md. It looks bad. It removes all the markdown formating, but mainly it lacks on the structure of a man page. Also, I think we will have to write a real one. As much as we like to write documentation.

**Comment by pgrange** [comment]
Merged your pull request #21 so that we have, at least, a basic man page.

I keep this issue open since I think we need something more elaborate to maintain both README.md and manpage with some common stuff.

Thanks for your contribution @n0vember-

**Comment by MichaelBitard** [comment]
Did you look at asciidoctor? github support them natively (README.adoc) and you can convert them to manpage with `-b manpage`

**Comment by pgrange** [comment]
Thanks @MichaelBitard for this great suggestion.

See https://github.com/pgrange/bash_unit/commit/5500d1e78a1380bc8a95c6250915b5f4497a96e3

**Comment by MichaelBitard** [comment]
Yeah!!!

**Comment by pgrange** [comment]
If you want to install bash_unit with a nice man page: https://github.com/pgrange/bash-unit_deb/releases/tag/v1.3.1-0
