### ISSUE TITLE
TAP output

### ISSUE THREAD

**Issue by smcv** [pgrange/bash_unit#28]
bash_unit currently outputs in its own human-readable format. It would be great if it could output in TAP http://testanything.org/ (a machine-readable but also reasonably human-readable test result format used by Perl, GLib, etc.), either as an option or all the time, so that "larger" testing systems like [GNOME installed-tests](https://wiki.gnome.org/Initiatives/GnomeGoals/InstalledTests) or perl's `prove` tool could test bash_unit scripts alongside ELF binaries, Perl scripts and so on.

The usual convention is for TAP test scripts to be an executable that you run, outputting machine-readable results on stdout. If bash_unit had TAP output, I think this would work if you write the `#!` line like this:

```
#!/usr/bin/env bash_unit

test_some_stuff () {
  fail "doesn't work"
}
```

**Comment by pgrange** [comment]
Hi, 
Thank you for this issue. I was not aware of this TAP format. That would be nice to support it. 

There is a gap in the specification between TAP version 12 and TAP version 13. The last add yaml syntax that is to be interpreted by some tool to give details in case of test failure.

I do not like this last idea. But if TAP version 12 is OK for your use case, I will see how to implement that. 

Regards,

**Comment by smcv** [comment]
I don't think many tools actually support TAP v13 - notably, TAP originated in Perl, and the Perl libraries don't produce v13. All the tools I've used just prepend `# ` to any line on stdout that isn't part of the machine-readable syntax (for instance the values of strings that should have been equal but weren't), making it a TAP v12 "diagnostic" (essentially a comment).

For instance this Perl code:

```perl
#!/usr/bin/perl
use warnings;
use strict;
use Test::More tests => 2;

is("aaa", "aaa");
is("aaa", "bbb");
```

produces this TAP:

```
1..2
ok 1
not ok 2
#   Failed test at t.pl line 7.
#          got: 'aaa'
#     expected: 'bbb'
# Looks like you failed 1 test of 2.
```

where the lines starting with `#` are not machine-readable, and are purely for a human reader to work out why the second check is failing.

**Comment by pgrange** [comment]
Right now, bash_unit outputs are spread all over the code.
I have to fix that mess before managing this issue.
Stay tuned.

**Comment by pgrange** [comment]
Had trouble accessing my computer but finally found some time to support tap format.

You can use this with:
 ```bash
bash_unit -f tap ...
`̀``

I still have to clean some parts of the code but the feature is usable.

bash_unit does not number tests and does not display test plan before running tests (number of tests to run). But as far as I understand the specification, this is a correct tap implementation.

Re-open this issue if you see any problem with this feature.

Regards,
