### ISSUE TITLE
Error in readme.adoc

### ISSUE THREAD

**Issue by rafernandez** [pgrange/bash_unit#45]
in readme.adoc :

> *assert_fail*
>     assert_fail <assertion> [message]
> Asserts that _assertion_ fails. This is the opposite of *assert*.
> _assertion_ fails if its evaluation returns a status code different from 0.

it's more like this :

_assertion_ fails if its evaluation returns a status code egal to 0.

You're confirming that behavior?

**Comment by pgrange** [comment]
I do not agree. Might be confusing but documentation is correct. 

By the way, your extract from documentation is missing ```assertion```:
```
assert_fail <assertion> [message]
```

So assert_fail succeeds if assertion fails. And assertion fails if its status code is different from 0.

Is it clearer stated like that ?

**Comment by rafernandez** [comment]
Yes, it is clearer.
My mistake was to confuse the status code of the assertion function (assert_fail) with the assertion.
Sorry for the inconvenience.
