### ISSUE TITLE
fake with some coreutils results in missing output

### ISSUE THREAD

**Issue by jakub-olczyk** [pgrange/bash_unit#53]
First of all, thank you for this awesome framework! :bowing_man: 

I would like to point out that `fake`ing some of the coreutils commands may result in output missing.
I was testing a bash script but I didn't want it to use the file system (at least not in all cases), so I faked some of the standard utils (within the test case) like this:
```bash
fake cat : 
fake sed :
```
And it broke the output for that test entirely (it didn't show up). After looking at the code that started the `assert` with `set -x` enabled my guess is that not all commands worked as intended afterwards. `fake` seemed so effective that even the assert didn't use the correct binaries. Here is a simple test case that reproduces the bug:
```bash
test_case_fake(){
    fake cat :
    fake sed :
    assert "true"
}
```
You will not see even the mention of this test case.

I am not familiar with Bash that much nor with the code of the framework, but maybe we could alias the binaries that are used within the `assert` so they are not mistakenly `fake`d within the test case? Or just warn in the docs that the `fake` cannot be used with all commands?

Cheers,
Jakub

**Comment by pgrange** [comment]
Thank you for using bash-unit.

I can see that some people like to play with the boundaries.I am almost disappointed that you did not try to fake `fake` itself :smiley: 

Joke aside, I am really thankfull for your issue because we never stumbled upon this kind of problem yet and, honestly, I did not consider that at all in bash_unit implementation.

I agree with you that we have to find a way to get rid of this problem and make bash_unit immune to fake itself. I think that it won't be that hard.

**Comment by pgrange** [comment]
Making some tests, I can reproduce a problem when faking  `cat` but I don't see any trouble when faking `sed`.

Said otherwise, the following test works just as expected on my computer:

```
test_case_fake(){
    fake sed :
    assert "true"
}
```

Did you encounter any specific issue when faking sed in your case?

**Comment by jakub-olczyk** [comment]
I am glad I can help this way with making the framework better :smile: 

Here is an example where `fake`ing `sed` produces different results:
```bash
test_fake_sed(){
    fake sed :
    assert "false" "this shouldn't happen"
}
```
Without `fake` I get:
```cmd
$ bash_unit -f tap tests/test_test 
# Running tests in tests/test_test
not ok ✗ test_fake
# shouldn't fail
# test_test:3:test_fake()
```
And after `fake`ing:
```cmd
$ bash_unit -f tap tests/test_test 
# Running tests in tests/test_test
not ok ✗ test_fake
```
I know that this is a minor issue compared to `fake`ing `cat` but still I think it is worth reporting :)

**Comment by pgrange** [comment]
I didn't have test exhibiting this issue so this is really helpful, thanks.

**Comment by pgrange** [comment]
Thanks for having raised this issue @jakub-olczyk I finally got some time to finish _solving it_.

I add a paragraph in doumentation to warn about that kind of problems and also made bash_unit more robust against some kinds of faking.

**Comment by jakub-olczyk** [comment]
Thank you for taking the time to solve this issue!
