### ISSUE TITLE
Test script syntax error does not fail run

### ISSUE THREAD

**Issue by dcasavant** [pgrange/bash_unit#54]
I am running bash_unit with travis-ci and I inadvertently introduced a syntax error into one of my test scripts.  The script failed to run but the build succeeded.  The failure should have been caught.

In Travis:
```yaml
script:
  - make test
  - ./bash_unit tests/test_*
```

Logs:
```
$ ./bash_unit tests/test_*
Running tests in tests/test_wait_for_job_success
test_wait_for_job_success: line 22: syntax error near unexpected token 'done'
test_wait_for_job_success: line 22: 'done'
The command "./bash_unit tests/test_*" exited with 0.
```

**Comment by pgrange** [comment]
Hi @dcasavant and think you for using bash_unit and reporting this issue.

Would you mind joining a sample test code so that we can reproduce easily your issue? Would be really appreciated since it would help fix it.

Regards,

**Comment by pgrange** [comment]
@dcasavant would you mind testing your code against the bash_unit version in branch [syntax_errors](https://github.com/pgrange/bash_unit/tree/syntax_errors) and see if it would be OK for you?

Regards,
