### ISSUE TITLE
Deb signing key is expired

### ISSUE THREAD

**Issue by duckythescientist** [pgrange/bash_unit#56]
From `apt update`:
```
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://pgrange.github.io/bash-unit_deb/debian unstable/ Release: The following signatures were invalid: EXPKEYSIG 5EB2C3CEC9B473E3 bash-unit (bash-unit signing key) <bash-unit@example.com>
W: Failed to fetch https://pgrange.github.io/bash-unit_deb/debian/unstable/Release.gpg  The following signatures were invalid: EXPKEYSIG 5EB2C3CEC9B473E3 bash-unit (bash-unit signing key) <bash-unit@example.com>
```

And from reading the key from https://pgrange.github.io/bash-unit_deb/keys.asc
```
pub   rsa4096 2017-09-22 [SC]
      DAE44E9F6F027E87768CBF985DDCF7B36B76543D
uid           bash-unit (bash-unit signing key) <bash-unit@example.com>
sub   rsa4096 2017-09-22 [E]
sub   rsa4096 2017-09-25 [S] [expired: 2019-10-09]
```

**Comment by pgrange** [comment]
Hi @duckythescientist,

Thank you for using bash_unit. I am so sorry it took me so long to answer your issue. Did not have so much time to give to bash_unit lately.

Trying to maintain a _.deb_ package has really been a pain in the neck and I don't want to  spend one more second of my life dealing with that. Some might say that it is not that hard to build deb packages, that you just have to do x, or just have to do y. And here I just have to update the key. But all maintaining a deb package and no play make me a dull boy.

So I just [removed](https://github.com/pgrange/bash_unit/commit/4f160a8d8c78f7be033375b2de8ed0fabcde5d64) this way of installing bash_unit from documentation.

FYI source code for the deb package is available here, would me more than happy to support anyone willing to take over:
https://github.com/pgrange/bash-unit_deb

Sorry,

**Comment by pgrange** [comment]
Thanks for your understanding.
