### ISSUE TITLE
Reporting problem failures related to Bash option -e

### ISSUE THREAD

**Issue by dodie** [pgrange/bash_unit#61]
Hi!

I noticed a small glitch when I use `set -e` in my code. For example:

```bash
#!/usr/bin/env bash

set -euo pipefail

function hello() {
	echo "something" | grep "else" # this will exit at this point, because this line finishes with a non-zero exit status
	echo "hello"
}

# Make sure that I can use source in the test
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
	hello
fi
```

I have the following test:

```bash
function test_1() {
	...
}
function test_fail_due_to_e() {
	source hello.sh
	result=$(hello)

	assert_equals 0 $?
	assert_equals "hello" "${result}"
}
function test_3() {
	...
}
```

Executing this tests fails with an error code, which is expected, but the report is a bit scrambled as there's no status indicator for the test that fails due to `-e`:

```
Running test_1... SUCCESS
Running test_fail_due_to_e... Running test_3... SUCCESS
```

Also, if I extract the sourcing from the `test_fail_due_to_e` function, like:

```bash
source hello.sh

function test_1() {
	...
}
function test_fail_due_to_e() {
	result=$(hello)
	assert_equals 0 $?
	assert_equals "hello" "${result}"
}
function test_3() {
	...
}
```

Then the whole test file will be missing from the report.

Would it be possible to include such failures in the report?

Thanks,
David

**Comment by pgrange** [comment]
Hi @dodie,
Sorry for the insane delay here.

**Comment by pgrange** [comment]
I'm trying to reproduce your first case but I can't see the same result as you. I've create hello.sh and test_hello with the following code inside and you can see what is the output of bash_unit for me.

```bash
#> cat hello.sh 
#!/usr/bin/env bash

set -euo pipefail

function hello() {
	echo "something" | grep "else" # this will exit at this point, because this line finishes with a non-zero exit status
	echo "hello"
}

# Make sure that I can use source in the test
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
	hello
fi
#> cat test_hello 
function test_fail_due_to_e() {
	source hello.sh
	result=$(hello)

	assert_equals 0 $?
	assert_equals "hello" "${result}"
}
#> ./bash_unit test_hello 
Running tests in test_hello
	Running test_fail_due_to_e... SUCCESS
```

Could you reproduce this and confirm you see the same thing as me?
Could you correct my code above so that I reproduce the same issue as yours?
