### ISSUE TITLE
Code coverage is planning?

### ISSUE THREAD

**Issue by roquie** [pgrange/bash_unit#67]
Just interesting it possible with bash or not ... 😄

**Comment by pgrange** [comment]
Hi @roquie,

Thanks for your question. I've never looked into it but it seems that this project might help if you need code coverage for bash: https://github.com/infertux/bashcov

I've quickly run the test of bash_unit through this tool. Not all test pass when run through this tool but it did give me some code coverage. I do not plan to dive into this too much but let me know if you have any success with it, I would be very interested.

Regards.

**Comment by pgrange** [comment]
Closing but feel free to re-open if you need anything.

Regards,

**Comment by roquie** [comment]
Oh, sorry I forgot about issue. I couldn't get `bashcov` to work with `bash_unit`.  Also it not works with `kcov` tool. Each time there was an empty code coverage :(

I migrated the code to `shellspec`. It supports `kcov` coverage tool from the box.
