### ISSUE TITLE
line 18 $'\r' command not found

### ISSUE THREAD

**Issue by humbienri** [pgrange/bash_unit#68]
Hello!
First of all, thank you for creating bash_unit! I'm looking forward to learning how to use it. Presently I am getting the above error when I just try to run any of the tests included in the repo. Maybe I am doing something wrong? I am on a Windows 10 laptop running Debian on WSL so may that be the issue?

Regardless of whether I try to run one of the suites, `test_core.sh` or all of the suites under `tests/`, I get the same error message.

Any advice would be appreciated. Thank you!

**Comment by pgrange** [comment]
Hi @humbienri,

Thanks for using bash_unit (or at least trying :) ). This looks like a Windows versus Unix end of line issue.

Maybe you could take a look at this question and see if _dos2unix_ helps to solve your issue:
https://stackoverflow.com/questions/11616835/r-command-not-found-bashrc-bash-profile/32912867

Let me know.

**Comment by humbienri** [comment]
Greetings Pascal!
Oh man, my heart sank when I read "end of THE line" in your reply as I thought there would be no workaround and I'd hit a dead end on this issue. Had to read it a couple of times to realize you meant a "line ending" issue. Whew!

Thanks for the lead on that Dos2Unix thingy although I don't have that utility/program on WSL's Debian distro. However, it looks like I am able to just use Notepad++ to open and save the files with Unix-style line endings and it appears to be working.

I had to do the resave stuff for both `bash_unit` and the `test_core.sh` script as well so I guess I'll need to do it for all of the files in your repo.

Thank you sir.
-Humberto
