### ISSUE TITLE
Feature Proposals

### ISSUE THREAD

**Issue by nemo1e8** [pgrange/bash_unit#72]
Great work on bash_unit! I've been using it for about six months and have made a few minor tweaks. Patch attached for your consideration.

Summary of changes:
- add output counters for # of successful or failing tests and # of assertions (this can be extended more generally to support persistent global variables that have been requested in another issue)
- add an -e option for an exact match to run a single test. For convenience, omit the "test" prefix so that you don't have to type it each time. 
- output total elapsed time (now only works on bash 5)
- add a default value to the terminal output function to avoid errors if running in strict mode
- minor formatting changes in a couple of places.

[bu_patch.txt](https://github.com/pgrange/bash_unit/files/6427429/bu_patch.txt)

**Comment by pgrange** [comment]
Hi @nemo1e8,

Thank you for your contribution and sorry for my insane delay in responding.

Your contribution addresses several, unrelated, issues. For each of them, I would be happy to understand the use case you have behind. But I don't see that happening with this global issue.

Feel free to open seperate merge requests for each of your proposal so we may discuss them one at a time.

Regards,
