### ISSUE TITLE
Failing `test_block_20` in `test_doc.sh`

### ISSUE THREAD

**Issue by TangoMan75** [pgrange/bash_unit#76]
Hi, Pascal 👋

Thank you for awesome tool, I'm planning to contribute to `bash_unit` project, adding CI/CD pipeline with github `workflow`

But tests keep failing :

![bash_unit](https://user-images.githubusercontent.com/14804833/132238076-250f8957-1f86-47d0-93ca-0e6ef53e7e54.png)

These look identical to me, I really don't get  it !?!

**Comment by pgrange** [comment]
Hi @TangoMan75,

Thank you for using bash_unit and even more for wanting to contribute.

I'm guessing you are running this test on macOS. Right?

If so, I've observed the same behavior but, it's a shame, I did not dig into it. So, right now, not sure where this is coming from :/

**Comment by pgrange** [comment]
Fixed by #77

**Comment by pgrange** [comment]
Seems to have been introduced in 973f67ba052f58a85e6e85c542047f3775fd446b and a CI would have helped.
One more reason for your kind contribution @TangoMan75  :)

**Comment by TangoMan75** [comment]
Wow, it's fixed already ! Thank you Pascal, thank you Christian, you are awesome !

Here's what I plan to do next  :
- Create a git hook to have every commit tested with bash_unit and linted with shellcheck locally
- Create a Github workflow to have every PR tested with bash_unit and linted with shellcheck
- From there I will try to resolve all shellcheck errors and warnings

**Comment by pgrange** [comment]
FYI, regarding shellcheck, you might be interested in this PR that I've shamely procrastinated: https://github.com/pgrange/bash_unit/pull/49

**Comment by TangoMan75** [comment]
> FYI, regarding shellcheck, you might be interested in this PR that I've shamely procrastinated: #49

Yeah... I saw that ;-)
