### ISSUE TITLE
bash_unit version tag

### ISSUE THREAD

**Issue by n0vember** [pgrange/bash_unit#83]
Hi,

There is actually no tag for current master branch version. It is said to be v1.8.0 in bash_unit itself but there is no such tag in your repo, therefore no release.

I maintain bash_unit package for Archlinux (on AUR) and can not provide this new version as I rely on tags to have matching versions between bash_unit and package.

Could you please create a tag for this version ?

Thanks

**Comment by pgrange** [comment]
Thanks @n0vember, I forgot to actually create the release :)

This is done now.

Regards,
