### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by mbeko** [pgrange/bash_unit#9]
What is the licence of bash_unit? Can it be used in a company context without being forced to publish source code (of the tests or the scripts under test)?

**Comment by pgrange** [comment]
Hi @mbeko I forgot to specify the licence, thank you for your issue.

bash_unit is covered by the GNU General Public License.

I am pretty sure that no software, commercial or not, would use bash_unit as a component of its final package. But more likely as a tool used to build this package.

So I do not consider code that uses bash_unit as a building brick bound to this license, neither the tests script not the code under test.

Regards,
Pascal.

**Comment by mbeko** [comment]
Great, thank you! Also very good to know about the types of code that are bound or not to the licence.
