### ISSUE TITLE
[feature] an assertion that compares numbers within a delta

### ISSUE THREAD

**Issue by masukomi** [pgrange/bash_unit#92]
## Use case:

I'm testing a timestamp that's been inserted in the db, but don't have a good way to "freeze time". So, I need to insert the record, get the current epoch time (presumably from `date`) then compare the two, but the second may have changed between the creation and the acquisition of the new date.

So, i want the ability to assert within a delta. 

There are, one presumes, many cases where you know a good approximation of a correct value but not the _exact_ value. Just like the need for regexp when you don't know the exact string that will come back, but do know its form. 

## Proposal

`assert_within_delta <expected num> <actual num> <max delta>`

Given an expectation of 5 and a delta of 2 this would match 3, 4, 5, 6, and 7

There should probably be a `positive` and `negative` variant.

`assert_within_positive_delta <expected_num> <actual_num> <max_delta>`

Given an expectation of 5 and a delta of 2 this would match 5, 6, and 7.

`assert_within_negative_delta <expected_num> <actual_num> <max_delta>`

Given an expectation of 5 and a delta of 2 this would match 3, 4, and 5.

**Comment by pgrange** [comment]
Hello @masukomi and happy new year. Also, sorry for the delay.

Thank you for using bash_unit and for this nicely shaped proposal.

Adding an assertion function in bash_unit itself is a tough one as we will have to maintain it forever then. But why not, your remark makes sense, it's quite close to asserting against regexp.

I've implemented your proposed `assert_within_delta` in PR #93 and would appreciate your feedback. In particular, you can look at the doc [here](https://github.com/pgrange/bash_unit/blob/time_delta/README.adoc#assert_within_delta).

I guess we can keep in mind `assert_within_positive_delta` and `assert_within_negative_delta` but postpone there implementation for later if somebody else express the need for them. Is is my understanding that you would only need `assert_within_delta` for your current use case. Correct?

**Comment by masukomi** [comment]
> But why not, your remark makes sense, it's quite close to asserting against regexp.

yay 🎉 :D 

>  Is is my understanding that you would only need assert_within_delta for your current use case. Correct?

correct. i'm doing time related tests so it'd always be in the same direction.  

I think the positive and negative are "nice-to-haves" rather than truly necessary for most folks.
